-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Carreras"
(
    "idCarrera" bigint NOT NULL,
    "descripción" "char" NOT NULL,
    PRIMARY KEY ("idCarrera")
);

CREATE TABLE IF NOT EXISTS public."Alumnos"
(
    "idAlumno" bigint NOT NULL,
    rut "char" NOT NULL,
    nombre name NOT NULL,
    "idCarrera" bigint NOT NULL,
    PRIMARY KEY ("idAlumno")
);

CREATE TABLE IF NOT EXISTS public."Profesores"
(
    "idProfesor" bigint NOT NULL,
    rut "char" NOT NULL,
    nombre name NOT NULL,
    PRIMARY KEY ("idProfesor")
);

CREATE TABLE IF NOT EXISTS public."EstadosTesis"
(
    "idSituación" bigint NOT NULL,
    "descripción estado" "char" NOT NULL,
    PRIMARY KEY ("idSituación")
);

CREATE TABLE IF NOT EXISTS public."Tesis"
(
    "idTesis" bigint NOT NULL,
    "idAlumno" bigint NOT NULL,
    "idArea" bigint NOT NULL,
    "idSituación" bigint NOT NULL,
    PRIMARY KEY ("idTesis")
);

CREATE TABLE IF NOT EXISTS public."AreasEstudio"
(
    "IdTema" "char" NOT NULL,
    "Descripción del Area" "char",
    PRIMARY KEY ("IdTema")
);

CREATE TABLE IF NOT EXISTS public."Comité"
(
    "idComite" bigint NOT NULL,
    "idTesis" bigint NOT NULL,
    PRIMARY KEY ("idComite")
);

CREATE TABLE IF NOT EXISTS public."Role"
(
    "idRol" bigint NOT NULL,
    "Descripción " "char" NOT NULL,
    PRIMARY KEY ("idRol")
);

CREATE TABLE IF NOT EXISTS public."Miembros_Comite"
(
    "idComite" "char" NOT NULL,
    "idProfesor" bigint NOT NULL,
    "idRol" bigint NOT NULL,
    "notaDocumento" real NOT NULL,
    "notaDefensa" real NOT NULL,
    PRIMARY KEY ("idComite")
);

ALTER TABLE IF EXISTS public."Alumnos"
    ADD FOREIGN KEY ("idCarrera")
    REFERENCES public."Carreras" ("idCarrera") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."EstadosTesis"
    ADD FOREIGN KEY ("idSituación")
    REFERENCES public."Tesis" ("idSituación") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Tesis"
    ADD FOREIGN KEY ("idAlumno")
    REFERENCES public."Alumnos" ("idAlumno") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."AreasEstudio"
    ADD FOREIGN KEY ("IdTema")
    REFERENCES public."Tesis" ("idArea") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Comité"
    ADD FOREIGN KEY ("idTesis")
    REFERENCES public."Tesis" ("idTesis") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Comité"
    ADD FOREIGN KEY ("idComite")
    REFERENCES public."Miembros_Comite" ("idComite") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Role"
    ADD FOREIGN KEY ("idRol")
    REFERENCES public."Miembros_Comite" ("idRol") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Miembros_Comite"
    ADD FOREIGN KEY ("idProfesor")
    REFERENCES public."Profesores" ("idProfesor") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;